# This workflow will build the project as webpack and deploy to Firebase Hosting
# For more information see: https://github.com/marketplace/actions/github-action-for-firebase

name: Webpack Build and Firebase Deploy

on:
  push:
    branches: 
      - 'release-production'

jobs:
  build:
    name: Webpack Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@master

    - name: Build Application
      run: npm run webpack:prod:main

    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build
    
  deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout the repository
      uses: actions/checkout@master

    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: build
        path: build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        PROJECT_ID: ccclubmanagement
